config/routes.rb
Blog::Application.routes.draw do

  resources :posts do
    resources :comments
  end
  
  root 'welcome#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :post, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  state_machine :state, :initial => :not_published do
    state :not_published
    state :published

    event :publish do
      transition :not_published => :published
    end

    event :unpublish do
      transition :published => :not_published
    end
  end

  has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def resource_post
    Post.find(params[:post_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "root", password: "123", only: :destroy

  def create
    comment = PostCommentType.new(params[:comment])
    comment.post = resource_post
    comment.save
    
    redirect_to post_path(resource_post)
  end
 
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "root", password: "123",
      except: [:index, :show]

  def new
    @post = PostType.new
  end

  def create
    @post = PostType.new(params[:post])
    
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = PostType.find(params[:id])
  end
  
  def index
    @posts = PostType.all
  end

  def edit
    @post = PostType.find(params[:id])
  end

  def update
    @post = PostType.find(params[:id])
 
    if @post.update(params[:post])
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = PostType.find(params[:id])
    @post.destroy
 
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_comment.html.haml
- if @post.comments.any?
  %table.table.table-striped
    %thead
      %tr
        %th= :commenter #model_class.human_attribute_name(:commenter)
        %th= :body #model_class.human_attribute_name(:body)
        %th= :created_at #model_class.human_attribute_name(:created_at)
        %th=t '.actions'
    %tbody
      - @post.comments.each do |comment|
        %tr
          %td= comment.commenter
          %td= comment.body
          %td=l comment.created_at, format: "%Y.%m.%d at %k:%M:%S"
          %td
            = link_to t('.destroy'), post_comment_path(@post, comment), :method => :delete, :data => { :confirm => t('.confirm', :default => 'Are you sure?') }, :class => 'btn btn-mini btn-danger'
- else
  %p no comments

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build], :html => { :class => 'form-horizontal' }) do |f|
  = f.input :commenter
  = f.input :body
  .form-actions
    = f.button :submit, :class => 'btn-primary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Simple blog"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Simple blog 
          .container.nav-collapse
            %ul.nav
              / %li= link_to "Link 1", "/path1"
              / %li= link_to "Link 2", "/path2"
              / %li= link_to "Link 3", "/path3"

    .container-fluid

      .row-fluid
        / .span3
        /   .well.sidebar-nav
        /     %ul.nav.nav-list
        /       %li.nav-header Sidebar
        /       %li= link_to "Link 1", "/path1"
        /       %li= link_to "Link 2", "/path2"
        /       %li= link_to "Link 3", "/path3"
        .span12
          = render_breadcrumbs
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Company 2013

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/_form.html.haml
= simple_form_for @post, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :text
  = f.input :state_event, as: :state_event

  .form-actions
    = f.button :submit, :class => 'btn'
    = link_to t('.cancel'), posts_path, :class => 'btn'

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/edit.html.haml
- model_class = Post
.page-header
  %h1=t '.edit', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<%= link_to 'New post', new_post_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.text %></td>
    <td><%= link_to 'Show', post_path(post) %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post_path(post),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/posts/index.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:text)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions'
  %tbody
    - @posts.each do |post|
      %tr
        %td= link_to post.id, post_path(post)
        %td= post.title
        %td= post.text
        %td=l post.created_at, format: "%Y.%m.%d at %k:%M:%S"
        %td
          = link_to t('.edit'), edit_post_path(post), :class => 'btn btn-mini'
          = link_to t('.destroy'), post_path(post), :method => :delete, :data => { :confirm => t('.confirm', :default => 'Are you sure?') }, :class => 'btn btn-mini btn-danger'

= link_to t('.new'), new_post_path, :class => 'btn btn-primary'

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/new.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>

app/views/posts/show.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @post.title
%p
  %strong= model_class.human_attribute_name(:text) + ':'
  %br
  = @post.text

%h2 Comments
/ = render @post.comments
= render "comments/comment"

%h2 Add a comment:
= render "comments/form"

.form-actions
  = link_to t('.back'), posts_path, :class => 'btn'
  = link_to t('.edit'), edit_post_path(@post), :class => 'btn'
  = link_to t('.destroy',), post_path(@post), :method => "delete", :data => { :confirm => t('.confirm', :default => 'Are you sure?') }, :class => 'btn btn-danger'

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "My Blog", controller: "posts" %>